name: Scala CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [21, 22, 23-ea]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test